### ISSUE TITLE
How to publish a conf package?

### ISSUE THREAD

**Issue by zajer** [ocaml-opam/opam-publish#102]
I would like to publish a conf package with `opam publish`.  
As far I understand such packages' opam files cannot have `url{}` tags but both documentation (https://opam.ocaml.org/doc/Packaging.html) and the patch (shown before submitting) indicate that it is required to add such tag.

So here is my question: Is there any way to publish such packages ?

**Comment by rjbou** [comment]
It is not possible ftm with opam-publish only. It will automatically add an url, but you can edit the pushed branch to remove it.
We need to add an `--conf`  option.

**Comment by zajer** [comment]
Thanks for the answer and considering this as an enhancement.
