### ISSUE TITLE
opam publish is generating branch-names with hashes

### ISSUE THREAD

**Issue by chetmurthy** [ocaml-opam/opam-publish#107]
When I use "opam publish", e.g. 
```
$ opam publish https://github.com/camlp5/camlp5/archive/rel8.00+alpha03.tar.gz

The following will be published:
  - 910cd131c845eadd2f4d1c8e6a0b497e-rel8 version 00+alpha03.tar.gz with opam file from the upstream archive
    archive at https://github.com/camlp5/camlp5/archive/rel8.00+alpha03.tar.gz
```
I get a gibberish branch-name (see above) instead of something like opam-publish-camlp5-rel8.00+alpha03.

I'm not sure where this is coming from at all.  Also, if it were possible that there's a flag for opan-publish, that does *everything* except actually filing the PR, that would be excellent, b/c then I could go in and fix this up, then file the PR myself.  The "-n" doesn't seem to do this -- when I try adding the flag, I get
```
Continue ? You will be shown the patch before submitting. [Y/n] y
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/bin/git rm -r packages/910cd131c845eadd2f4d1c8e6a0b497e-rel8/910cd131c845eadd2f4d1c8e6a0b497e-rel8.00+alpha03.tar.gz" exited
        with code 128 "fatal: pathspec 'packages/910cd131c845eadd2f4d1c8e6a0b497e-rel8/910cd131c845eadd2f4d1c8e6a0b497e-rel8.00+alpha03.tar.gz' did not match
        any files"
```

**Comment by rjbou** [comment]
Will be fixed in opam by ocaml/opam#4401, need to update opam file to add a `opam-format >= 2.1.0~beta3` when it will be released to resolve completely

**Comment by chetmurthy** [comment]
Lovely!  Um, not sure how I'd find out, and I don't want to ask on the discussion forum [too esoteric] but ..... where would one look to learn what versions of opam are deployed as part of the opam-repository CI infrastructure?  (hence, what versions are safe to specify in opam files destined for the repository?)

**Comment by rjbou** [comment]
The opam repository takes only 2.0 opam files, with some constraints (no version field, no pin-depends, current version referenced by the variable, etc.).
For opam version that runs in CI, if you have a dependency on opam, you can refer to any released opam version, as CI will install it as an opam package in the job.

**Comment by chetmurthy** [comment]
Excellent!  Thank you!  BTW, I am now using opam 2.1.0-beta3 and am liking the improvements in things like filters!

**Comment by rjbou** [comment]
Happy to hear! Thank you! :D
