### ISSUE TITLE
opam publish token generation did not work

### ISSUE THREAD

**Issue by mcclure** [ocaml-opam/opam-publish#115]
Today I attempted to run `opam publish`. I entered my Github username and password to generate a token. I got this error:

![image](https://user-images.githubusercontent.com/277318/99846328-20068200-2b44-11eb-9dc9-30375f79ea57.png)

I do not know what this means. I don't know if this is a global github thing or if it is something special about my account. My username and password were correct. I successfully used `opam publish` about two months ago, but later deleted my `.opam`.

I was able to make opam publish work by manually generating a token, but I think this error should be looked into anyway.

**Comment by AltGr** [comment]
Thanks for reporting! Have you enabled 2FA in github? And, more importantly, what version of `ocaml-github` are you using (`opam show github -f version`) ? This is the library that drives the authentication and raises this error, so you might want to also check https://github.com/mirage/ocaml-github/issues , if you're interested.

**Comment by mcclure** [comment]
2FA was not on while I was performing the tests. I could log in with l/p through the web interface.

`opam show github -f version` is `4.3.2`.

**Comment by Aaylor** [comment]
The issue seems to be related to #119, and is due to the GitHub Authorizations API being removed. It is now necessary to generate manually your personal access token.

**Comment by AltGr** [comment]
Fixed by #121 (Github dropped support anyway)
Thanks for reporting, still :)
