### ISSUE TITLE
Manual Github Token UI is confusing

### ISSUE THREAD

**Issue by mcclure** [ocaml-opam/opam-publish#116]
When you run `opam publish`, it says:

```
Continue ? You will be shown the patch before submitting. [Y/n] y
No Github token found. Should I generate one ?
(your credentials will be required. If you do not have a Github account, you
can create one at https://github.com/join) [Y/n]
```

If you say `[y]`, it will ask you for your Github username and password. If you say `[n]`, it will ask you to create a github token manually and paste it into the UI.

However, when I ran this, I had a problem. My preference was to *not* type my Github username and password into a command line script I only partly  understand. (Moreover, as explained in #115, the username/password entry was not working for me). What I *wanted* to do was create a Github access token through the web UI and paste it in. But *I did not know I could do this!* I wasted a decent amount of time trying to make the l/p route work (and even tried creating a ocaml%opam-repository.token file by hand, which ended badly). If I had just answered [n] to "should I generate one?" I could have gotten what I wanted immediately. But there was nothing in the UI to indicate "n" means "generate a token separately".

My **expected behavior** is that the message be clearer. For example, you could say 

`Should I generate one automatically? (y) Or would you prefer to create one on github.com yourself? (n)`

**Comment by AltGr** [comment]
Fixed by #121 (Github dropped support anyway)
Thanks for reporting, still :)
