### ISSUE TITLE
Publish 2.0.3?

### ISSUE THREAD

**Issue by phated** [ocaml-opam/opam-publish#122]
I just tried to kick off a build that relies on the `--no-browser` flag and noticed it only picked up 2.0.2 of opam-publish. I believe the 2.0.3 version needs to be published to opam.

**Comment by dra27** [comment]
Actually it isn’t released either... however, you should be able to do `opam pin add opam-publish --dev-repo` and the plug-in will update

**Comment by phated** [comment]
Hmm, if I back out the release to make that work, all my CI is going to get screwed up again (I just finished a ton of git surgery to fix a different mistake).

Is there a reason it isn't released or published?

**Comment by dra27** [comment]
> Hmm, if I back out the release to make that work, all my CI is going to get screwed up again (I just finished a ton of git surgery to fix a different mistake).

I don't follow this? Wherever you're using `opam-publish` in your CI, adding `opam pin add -yn opam-publish --dev-repo` should enable 2.0.3.

**Comment by phated** [comment]
When you base GitHub Actions on a release, you can't update the CI workflow files and run it against the release. It will always use the workflow files at the SHA of that release. So I can't apply your suggestion against my release, only future releases. If you could publish opam-publish 2.0.3, I could just re-run CI and it would use the new version.

**Comment by dra27** [comment]
Ah, I see. @AltGr had been using the master branch for a while so it's had enough testing to be released - it was merged to opam-repository a few hours ago.

**Comment by phated** [comment]
❤️ Awesome, thank you! We were able to use it to successfully publish yesterday.
