### ISSUE TITLE
[feature request] opam-publish should never send a PR without a url field (add a new --empty-url option to bypass that)

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-opam/opam-publish#124]
People sending empty packages to opam-repository is very very common. Such restriction would be very appreciated.

**Comment by AltGr** [comment]
I am actually curious through which workflow they do that ? It might also be that `opam-publish` doesn't do enough efforts to find the expected URL in some cases ?

**Comment by kit-ty-kate** [comment]
Usually I think it is something like that:
```
$ git tag v0.2.3
# .. should have been a git push here
$ opam publish
```

**Comment by kit-ty-kate** [comment]
In https://github.com/ocaml/opam-repository/pull/18623#issuecomment-831225967 the maintainer had their main repository simply be **not github** ^^"

Steps to reproduce:
```
$ git clone https://framagit.org/zoggy/ocaml-iri
$ cd ocaml-iri
$ opam publish

The following will be published:
  - ocaml-iri version 0.5.0 with opam file at /tmp/ocaml-iri/opam

[WARNING] These will be virtual packages: ocaml-iri.0.5.0

Continue ? You will be shown the patch before submitting. [Y/n]
```

**Comment by kit-ty-kate** [comment]
Another case here: https://github.com/ocaml/opam-repository/pull/18806
