### ISSUE TITLE
How to use existing PR to opam-repository ?

### ISSUE THREAD

**Issue by zoggy** [ocaml-opam/opam-publish#125]
Hi,

I used opam-publish to create a PR to opam-repository for a new version of a library. There were some problems (opam-publish removed the name: field of my opam file, for example...). I made a new archive and used the same opam-publish command:
````
opam publish https://framagit.org/zoggy/ocaml-iri/-/archive/0.5.0/ocaml-iri-0.5.0.tar.bz2
````
and opam-publish created a new PR, instead of reusing the previous one. It I remember correctly, back in 2017 it used to add comment to existing PR. How to get this behaviour to avoid creating new PR for each fix of the archive ?

**Comment by AltGr** [comment]
Indeed the feature is still there, but `opam-publish` is based on the package name to decide what the PR should be: here your package changed name (or at least that's how it was seen by the subsystem), so it couldn't detect the already existing PR.
