### ISSUE TITLE
Feature wish: Add a `--yes` flag to automatically accept Confirm questions

### ISSUE THREAD

**Issue by erikmd** [ocaml-opam/opam-publish#132]
In order to be able to use `opam publish` in "batch mode", directly from a GH Action, I believe it would be very handy to have a `-y` or so flag, a bit like opam 🙂

Note: I tried `yes | opam publish --no-browser --msg-file=CHANGES.md --tag $tag_name $user/$repo` but got:
```
You will be shown the patch before submitting.
Please confirm the above data. Continue ?  [Y/n] n
yes: standard output: Broken pipe
Error: Process completed with exit code 10.
```

**Comment by phated** [comment]
It seems that v2.1.0 of opam-publish doesn't respect `OPAMYES=1` for some reason. I can't quite understand why.

**Comment by phated** [comment]
I downgraded to opam-publish v2.0.3 in my local env and it works again.
