### ISSUE TITLE
Adopt the OCaml Code of Conduct

### ISSUE THREAD

**Issue by rikusilvola** [ocaml-opam/opam-publish#152]
The OCaml Code of Conduct can be found in [ocaml/code-of-conduct](https://github.com/ocaml/code-of-conduct) and has been discussed [in this Discourse thread](https://discuss.ocaml.org/t/ocaml-community-code-of-conduct/10494).

We propose adopting it for ocaml-opam/opam-publish as well.

Once adopted, the list at [ocaml/code-of-conduct](https://github.com/ocaml/code-of-conduct) needs to be updated.

- [ ] #151 
- [ ] Update [List of Adopters](https://github.com/ocaml/code-of-conduct/blob/main/list-of-adopters.md)

**Comment by punchagan** [comment]
This can be closed once https://github.com/ocaml/code-of-conduct/pull/20 is merged.

**Comment by punchagan** [comment]
https://github.com/ocaml/code-of-conduct/pull/20 has now been merged.

**Comment by rjbou** [comment]
Thanks!
