### ISSUE TITLE
`opam-publish submit` interactive behaviour improvements

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-opam/opam-publish#20]
I think it would be nice to 
1. Provide a command line option to disable `[xdg-]open`. In that case the PR URI should be output on stdout. 
2. On osx use `open -g` ([man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/open.1.html)) in order to open the webpage in the background. It's always a little bit surprising to loose focus of your terminal without you deciding that. Usually there's one or two things I want to do in the terminal after I `submit`ted, having to switch back to the terminal is annoying. Unfortunately it doesn't seem that `xdg-open` supports that. 

Some people may disagree with 2. Here are other alternatives:

a) Have a switch to indicate the _use_ of `open` rather than one preventing its use. But usually I want the `open`, just not immediately after the submit. 
b) Forget `open`s on `submit`s and have a another command (`review`, `show` ?) that `open`s the PR of any submitted package that has not been merged yet. 

Actually I think b) would be best.

**Comment by AltGr** [comment]
How about asking the user ?

```
Pull-request page: http://xxx
Open in browser now ? [Y/n]
```

**Comment by dbuenzli** [comment]
Well as I said, usually I want to open it just not now (or in the background). So that wouldn't help.
