### ISSUE TITLE
Github API used by "opam publish" is deprecated?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml-opam/opam-publish#97]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

I just used "opam publish" to publish a package using a Github token.  The Github token I used was acquired immediately prior, for the purpose of this publish operation.  I received an email right after I published from Github, informing me that the API I'd used was deprecated.  I figured I should file an issue with opam about it ... ?

```
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http), 1 (version-controlled) (default repo at 4ddb5d06)
# pinned            0
# current-switch    4.09.0

```
On February 5th, 2020 at 21:23 (UTC) your personal access token (Ocaml Opam publishing) using ocaml-github ocaml-cohttp/2.5.0 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

**Comment by rjbou** [comment]
Thanks for the report! Moving this issue to opam-publish tracker.

What is your installed version of `github` and `github-unix` packages ?

**Comment by fpottier** [comment]
+1, I just received a similar email message from GitHub.

An excerpt from the email:

```
On February 7th, 2020 at 12:26 (UTC) your personal access token (opam-publish access token (DT-64014)) using ocaml-github ocaml-cohttp/2.5.0 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
```

I am using `opam-publish` 2.0.2.
And the versions of `github` and `github-unix` that I have are as follows:

```
$ opam show github github-unix

<><> github: information on all versions ><><><><><><><><><><><><><><><><><><><>
name                   github
all-installed-versions 3.1.0 [4.05.0]  4.2.0 [4.09.0]
all-versions           0.3.0  0.3.1  0.3.2  0.3.3  0.4.0  0.4.1  0.4.2  0.4.3
                       0.5.0  0.6.0  0.6.1  0.7.0  0.7.1  0.8.0  0.8.1  0.8.2
                       0.8.3  0.8.4  0.8.5  0.8.6  0.9.0  0.9.1  0.9.2  0.9.3
                       0.9.4  1.0.0  1.1.0  2.0.0  2.0.1  2.0.2  2.0.3  2.1.0
                       2.2.0  2.3.0  3.0.0  3.0.1  3.1.0  4.0.0  4.1.0  4.2.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       4.2.0
repository    default
url.src:      "https://github.com/mirage/ocaml-github/releases/download/4.2.0/github-unix-4.2.0.tbz"
url.checksum:
          "sha256=10fecdb5d58ab4dac85d615e89d0e8eab2413a243bad6ad2f4a7f8783704d745"
          "sha512=6b89941480f9fc59aedf5b4844b0b1892229e50e034c86d4a1c5ff9afcc10778262d23cee72f62a663873a52cfece676802fd4e3af16aefb0eec24a458761484"
homepage:     "https://github.com/mirage/ocaml-github"
bug-reports:  "https://github.com/mirage/ocaml-github/issues"
dev-repo:     "git+https://github.com/mirage/ocaml-github.git"
authors:      "Anil Madhavapeddy"
              "David Sheets"
              "Andy Ray"
              "Jeff Hammerbacher"
              "Thomas Gazagnaire"
              "Rudi Grinberg"
              "Qi Li"
              "Jeremy Yallop"
              "Dave Tucker"
maintainer:   "Anil Madhavapeddy <anil@recoil.org>"
license:      "MIT"
depends:      "ocaml" {>= "4.03.0"}
              "dune" {>= "1.10"}
              "uri" {>= "1.9.0"}
              "cohttp" {>= "0.99.0"}
              "cohttp-lwt" {>= "0.99"}
              "lwt" {>= "2.4.4"}
              "atdgen" {>= "2.0.0"}
              "yojson" {>= "1.6.0"}
              "stringext"
synopsis      GitHub APIv3 OCaml library
description
          This library provides an OCaml interface to the
          [GitHub APIv3](https://developer.github.com/v3/) (JSON).
          It is compatible with [MirageOS](https://mirage.io) and also compiles
          to pure
          JavaScript via [js_of_ocaml](http://ocsigen.org/js_of_ocaml).

<><> github-unix: information on all versions <><><><><><><><><><><><><><><><><>
name                   github-unix
all-installed-versions 3.1.0 [4.05.0]  4.2.0 [4.09.0]
all-versions           3.0.0  3.0.1  3.1.0  4.0.0  4.1.0  4.2.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       4.2.0
repository    default
url.src:      "https://github.com/mirage/ocaml-github/releases/download/4.2.0/github-unix-4.2.0.tbz"
url.checksum:
          "sha256=10fecdb5d58ab4dac85d615e89d0e8eab2413a243bad6ad2f4a7f8783704d745"
          "sha512=6b89941480f9fc59aedf5b4844b0b1892229e50e034c86d4a1c5ff9afcc10778262d23cee72f62a663873a52cfece676802fd4e3af16aefb0eec24a458761484"
homepage:     "https://github.com/mirage/ocaml-github"
bug-reports:  "https://github.com/mirage/ocaml-github/issues"
dev-repo:     "git+https://github.com/mirage/ocaml-github.git"
authors:      "Anil Madhavapeddy"
              "David Sheets"
              "Andy Ray"
              "Jeff Hammerbacher"
              "Thomas Gazagnaire"
              "Rudi Grinberg"
              "Qi Li"
              "Jeremy Yallop"
              "Dave Tucker"
maintainer:   "Anil Madhavapeddy <anil@recoil.org>"
license:      "MIT"
depends:      "ocaml" {>= "4.03.0"}
              "dune" {>= "1.10"}
              "github" {= version}
              "cohttp" {>= "0.99.0"}
              "cohttp-lwt-unix" {>= "0.99.0"}
              "stringext"
              "lambda-term" {>= "2.0"}
              "cmdliner" {>= "0.9.8"}
              "base-unix"
synopsis      GitHub APIv3 Unix library
description
          This library provides an OCaml interface to the [GitHub
          APIv3](https://developer.github.com/v3/)
          (JSON).  This package installs the Unix (Lwt) version.
```

**Comment by chetmurthy** [comment]
<><> github: information on all versions ><><><><><><><><><><><><><><><><><><><>
name                   github
all-installed-versions 4.2.0 [4.09.0]
all-versions           0.3.0  0.3.1  0.3.2  0.3.3  0.4.0  0.4.1  0.4.2  0.4.3  0.5.0  0.6.0  0.6.1  0.7.0  0.7.1  0.8.0  0.8.1  0.8.2  0.8.3  0.8.4  0.8.5  0.8.6  0.9.0  0.9.1  0.9.2  0.9.3  0.9.4  1.0.0  1.1.0  2.0.0  2.0.1  2.0.2  2.0.3  2.1.0  2.2.0
                       2.3.0  3.0.0  3.0.1  3.1.0  4.0.0  4.1.0  4.2.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       4.2.0
repository    default
<><> github-unix: information on all versions <><><><><><><><><><><><><><><><><>
name                   github-unix
all-installed-versions 4.2.0 [4.09.0]
all-versions           3.0.0  3.0.1  3.1.0  4.0.0  4.1.0  4.2.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       4.2.0
repository    default

**Comment by rjbou** [comment]
Thanks for the  information. I opened an issue in `ocaml-github` tracker.

**Comment by XVilka** [comment]
See also https://github.com/ocaml-opam/opam-publish/issues/104

**Comment by mseri** [comment]
Can we rely on `graphql-ppx` for the package though? The native version is no longer documented in practice, and the focus of the library seems to be now mostly on bucklescript

**Comment by Zimmi48** [comment]
FTR, contrary to what the title of this issue seems to indicate, the content of the deprecation message clearly says that it's the authentication method that is getting deprecated, not the REST API itself. So while I can only support a migration to GraphQL (cf. also what I wrote about this in the related `ocaml-github` issue), it is completely orthogonal to this issue which is just about moving the authentication to the HTTP headers: basically all you need is a header `("Authorization", "bearer TOKEN")` instead of passing this authorization token through the URL.

As for using GraphQL (which, I insist is orthogonal to the present issue, and thus not as urgent), it would be pretty easy IMHO. You can depend on `graphql_ppx` for this and you can inspire from what we do at https://github.com/coq/bot (cf. the `bot-components` folder). It seems that the upcoming 1.0 version is again focusing more on the Bucklescript part but the latest released version (available through opam BTW) supports native quite well and this is what we use in our coqbot project. If more people on the OCaml side start to rely on this library, this will also help ensure that native is an important use case that keeps being supported.

**Comment by roddyyaga** [comment]
Am I right in saying:

- This has been fixed in the latest version of `ocaml-github` (4.3.0), see [here](https://github.com/mirage/ocaml-github/pull/230)
- But version 4.3.0 breaks GitHub authorization in some other way(s)
- The new bug is on the `opam-publish` side

?

**Comment by Aaylor** [comment]
Hello,

The issue was effectively on `ocaml-github` side. With the change made on authentication on `4.3.0`, idempotent requests (e.g. `GET`, ...) were correctly authentified; but other requests (as `POST`, `PUT` and `PATCH`) were not correctly authentified due to the missing authentication header.

The authentification problem should be fixed on `ocaml-github.4.3.2` (being currently deployed on `opam`: ocaml/opam-repository#17239).

Do not hesitate to ping me, or to open a new issue on `ocaml-github` if another problem occurs: unfortunately, I was not aware (and thus, I couldn't react) of the authentication issue you faced off since march :(

Sorry for the inconvenience!

**Comment by rjbou** [comment]
Fixed with new `github.4.3.2`. Thanks
