### ISSUE TITLE
opam publish fails with 401 Unauthorized

### ISSUE THREAD

**Issue by erhangundogan** [ocaml-opam/opam-publish#99]
Hello.

I have tried to `opam publish` to publish my repo https://github.com/erhangundogan/crawler you can se the output below. What could be the problem?

<img width="1090" alt="Screenshot 2020-03-09 at 00 27 35" src="https://user-images.githubusercontent.com/818450/76173169-32e74b00-619d-11ea-83e1-8f143e9b4800.png">

**Comment by rjbou** [comment]
Thanks for the report.
What is your installed version of `github` and `github-unix` ?

**Comment by erhangundogan** [comment]
Both v4.3.0

**Comment by rjbou** [comment]
It is related to some github authentication mechanism deprecation. `github` updated according, but it resulted in this bug in `opam-publish` (it needs some github interaction rewriting).
You can use ftm `github{,-unix} < 4.3.0`, and you'll receive a mail about the deprecation.
Related to #97

**Comment by rjbou** [comment]
I reopen it until the rewriting is done :)

**Comment by dakk** [comment]
> It is related to some github authentication mechanism deprecation. `github` updated according, but it resulted in this bug in `opam-publish` (it needs some github interaction rewriting).
> You can use ftm `github{,-unix} < 4.3.0`, and you'll receive a mail about the deprecation.
> Related to #97

@rjbou  I have the same problem but I didn't understand how to bypass the error

**Comment by Aaylor** [comment]
Hello,

You can take a look at my comment made on #97, the issue should be fixed with the new upcoming version `4.3.2`. Feel free to open a new issue on `ocaml-github`, or to ping me directly, if you face another issue with `ocaml-github`.
Sorry, for the inconvenience!

**Comment by rjbou** [comment]
Fixed with new `github.4.3.2`. Thanks
